name: Inseego

env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: openwrt-25.12  # 明确锁定 25.12 分支
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: IPQ807X.config # 我们后续会替换这个配置
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
